
# About  {.unnumbered}

## Course content {.unnumbered}

This course introduces key concepts in population genomics, from generating population genetic data sets to the most common population genetic analyses and association studies. The first part focuses on the generation of population genetic data sets. The rest of the course introduces methods for full genome population genetic analysis and their theoretical background. Course topics include analysis of demography, population structure, recombination,  selection, and genome-wide association with human health and disease.
Description of qualifications

## Objectives of the course

The participants will after the course have detailed knowledge of the methods and applications required to perform a typical population genomic study.

## Learning outcomes and competences

The participants must at the end of the course be able to:

- Identify an experimental platform relevant to a population genomic analysis
- Apply commonly used population genomic methods
- Explain the theory behind common population genomic methods
- Reflect on strengths and limitations of population genomic methods
- Interpret and analyze results of population genomic inference
- Formulate population genetics hypotheses based on data.
