---
panels: true
---

::: {.content-hidden when-meta="panels"}
# Week plan {.unnumbered}
:::

[Schedule for student presentations](https://docs.google.com/spreadsheets/d/1t0UzO-aOj53uVPh39hG9EYR0AvrWdXj-uPFNdFWH660/edit?usp=sharing)

<!-- ------------------------------------------------------------------------------------------------------------------------------------------- -->

## 1 {.unnumbered}

### **Week 5**

**Lectures:** Course intro and overview: Coop chapt 1, 2, 3
**Exercises:** [Cluster practicals](exercises/cluster_practicals/README.md)

<!-- ------------------------------------------------------------------------------------------------------------------------------------------- -->

## 2 {.unnumbered}

### **Week 6**

**Lectures:** The Coalescent and the ARG: Coop chapt 4, [Paper: Simons Genome Diversity Project] <!-- [Paper on Platypus] -->

**Exercises:** [Browsing ARGs](https://github.com/kaspermunch/PopulationGenomicsCourse/tree/master/Exercises/mapping_and_calling)

<!-- **Exercises:** [Read mapping and base calling](https://github.com/kaspermunch/PopulationGenomicsCourse/tree/master/Exercises/mapping_and_calling) -->

<!-- ------------------------------------------------------------------------------------------------------------------------------------------- -->

## 3 {.unnumbered}

### **Week 7**

**Reading:**

**Lectures:** Past population demography, HMMs, ARG, [Paper on PSMC](https://www.nature.com/articles/nature10231)

**Exercises:** [Estimating past population sizes](https://github.com/kaspermunch/PopulationGenomicsCourse/tree/master/Exercises/demography)

<!-- ------------------------------------------------------------------------------------------------------------------------------------------- -->

## 4 {.unnumbered}

### **Week 8**

**Lectures:** Recombination, Phasing, HMMs, ARG, PSMC [Paper on tree inference](https://www.nature.com/articles/s41588-019-0484-x), [Review on recombination rate](https://www.nature.com/articles/s41576-020-0240-1)

**Exercises:** [Phasing and recombination](https://github.com/kaspermunch/PopulationGenomicsCourse/tree/master/Exercises/phasing)

## 5 {.unnumbered}

<!-- ------------------------------------------------------------------------------------------------------------------------------------------- -->

### **Week 9**

**Lectures:** Population structure, Incomplete lineage sorting\*\*, HMMs, Coop chapt 6, [Review on ILS](https://doi.org/10.1146/annurev-genet-120213-092532)

**Exercises:** [Inference of population structure and admixture](https://github.com/kaspermunch/PopulationGenomicsCourse/tree/master/Exercises/population_structure)

<!-- ------------------------------------------------------------------------------------------------------------------------------------------- -->

## 6 {.unnumbered}

### **Week 10**

**Lectures:** Admixture, HMMs, [Review on admixture](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1007349), [Paper on admixture inference](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1007641)

**Exercises:** [Tree sequences](https://github.com/kaspermunch/PopulationGenomicsCourse/tree/master/Exercises/tree_sequences)

<!-- ------------------------------------------------------------------------------------------------------------------------------------------- -->

## 7 {.unnumbered}

### **Week 11**

**Lectures:** Direct and linked selection, Coop chapt 12, 13, revisit [Paper on tree inference](https://www.nature.com/articles/s41588-019-0484-x)

**Exercises:** [Inference of positive selection](https://github.com/kaspermunch/PopulationGenomicsCourse/tree/master/Exercises/selection)

<!-- ------------------------------------------------------------------------------------------------------------------------------------------- -->

## 8 {.unnumbered}

### **Week 12**

**Lectures:** Projects, Popgen overview [Mandatory project description](https://github.com/kaspermunch/PopulationGenomicsCourse/tree/master/Projects)

**Exercises:** [GWAS quality control](https://github.com/kaspermunch/PopulationGenomicsCourse/tree/master/Exercises/GWAS_QC)

<!-- ------------------------------------------------------------------------------------------------------------------------------------------- -->

## 9 {.unnumbered}

### **Week 13**

**Lectures:** GWAS review, Population stratification review, Coop 99-120

**Exercises:** [Association testing](https://github.com/kaspermunch/PopulationGenomicsCourse/tree/master/Exercises/GWAS_association)

<!-- ------------------------------------------------------------------------------------------------------------------------------------------- -->

## 10 {.unnumbered}

### **Week 14**

**Reading:**

**Lectures:** Heritability, [Review on heritability and LMM](https://dl.acm.org/doi/10.1145/2817827) ; Coop Sec 2.2 (p23-36) + Chapt 7 (p119-142)

**Exercises:** [Estimating heritability](https://github.com/kaspermunch/PopulationGenomicsCourse/tree/master/Exercises/heritability)

<!-- ------------------------------------------------------------------------------------------------------------------------------------------- -->

## 11 {.unnumbered}

### **Week 15**

**Lectures:** Project

**Exercises:** Project

## 12 {.unnumbered}

<!-- ------------------------------------------------------------------------------------------------------------------------------------------- -->

### **Week 16**

**Lectures:** Project

**Exercises:** SKÆRTORSDAG

<!-- ------------------------------------------------------------------------------------------------------------------------------------------- -->

## 13 {.unnumbered}

### **Week 17**

**Lectures:** 2. PÅSKEDAG

**Exercises:** Project

<!-- ------------------------------------------------------------------------------------------------------------------------------------------- -->

## 14 {.unnumbered}

### **Week 18**

**Lectures:** Project

**Exercises:** Project



<!-- Curriculum links -->
[Paper: Simons Genome Diversity Project]: https://www.nature.com/articles/nature18964                                                                                                                                                                               
[Paper on Platypus]: https://www.nature.com/articles/ng.3036                                                                                                                                                             
[Paper on PSMC]: https://www.nature.com/articles/nature10231                                                                                                                                                          
[Paper on tree inference]: https://www.nature.com/articles/s41588-019-0484-x
[Review on recombination rate]: https://www.nature.com/articles/s41576-020-0240-1
[Review on ILS]: https://doi.org/10.1146/annurev-genet-120213-092532
[Review on admixture]: https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1007349
[Paper on admixture inference]: https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1007641
[Paper on tree inference]: https://www.nature.com/articles/s41588-019-0484-x                                                                                                                                             
[Paper on exploiting ARGs in GWAS]: https://www.nature.com/articles/s41588-023-01379-x

<!-- https://brightspace.au.dk/d2l/common/viewFile.d2lfile/Content/L2NvbnRlbnQvZW5mb3JjZWQvMTY2Mjk3LUxSNDA2NTEvYXJnbmVlZGxlLnBkZg/argneedle.pdf?ou=166297 -->

[Tree sequences]: https://github.com/kaspermunch/PopulationGenomicsCourse/tree/master/Exercises/tree_sequences
[GWAS review]: https://
[Population stratification review]: https://
[Review on heritability and LMM]: https://dl.acm.org/doi/10.1145/2817827
[Genetic architecture review]: https://
[Article on "omnigenic" model]: https://

<!-- Exercise links -->
[Cluster practicals]: https://github.com/kaspermunch/PopulationGenomicsCourse/tree/master/Exercises/cluster_practicals
[Read mapping and base calling]: https://github.com/kaspermunch/PopulationGenomicsCourse/tree/master/Exercises/mapping_and_calling
[Estimating past population sizes]: https://github.com/kaspermunch/PopulationGenomicsCourse/tree/master/Exercises/demography
[Estimating past population sizes]: https://github.com/kaspermunch/PopulationGenomicsCourse/tree/master/Exercises/demography
[Phasing and recombination]: https://github.com/kaspermunch/PopulationGenomicsCourse/tree/master/Exercises/phasing
[Inference of population structure and admixture]: https://github.com/kaspermunch/PopulationGenomicsCourse/tree/master/Exercises/population_structure
[Detecting archaic ancestry in modern humans]: https://github.com/kaspermunch/PopulationGenomicsCourse/tree/master/Exercises/admixture
[Tree sequences]: https://github.com/kaspermunch/PopulationGenomicsCourse/tree/master/Exercises/tree_sequences
[Inference of positive selection]: https://github.com/kaspermunch/PopulationGenomicsCourse/tree/master/Exercises/selection
[GWAS quality control]: https://github.com/kaspermunch/PopulationGenomicsCourse/tree/master/Exercises/GWAS_QC
[Association testing]: https://github.com/kaspermunch/PopulationGenomicsCourse/tree/master/Exercises/GWAS_association
[Estimating heritability]: https://github.com/kaspermunch/PopulationGenomicsCourse/tree/master/Exercises/heritability

<!-- Project links -->
[Mandatory project description]: https://github.com/kaspermunch/PopulationGenomicsCourse/tree/master/Projects
